//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpamNetProject.PLL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to balance.
        /// </summary>
        public static string ACCOUNT_ADDTOBALANCE {
            get {
                return ResourceManager.GetString("ACCOUNT_ADDTOBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string ACCOUNT_BALANCE {
            get {
                return ResourceManager.GetString("ACCOUNT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ACCOUNT_EDIT_CONFIRMPASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_CONFIRMPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ACCOUNT_EDIT_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string ACCOUNT_EDIT_FIRSTNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ACCOUNT_EDIT_LANGUAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNT_EDIT_PASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        public static string ACCOUNT_EDIT_SAVEPROFILE {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ACCOUNT_EDIT_SURNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string ACCOUNT_EDIT_TIMEZONE {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_TIMEZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string ACCOUNT_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string ACCOUNT_EDITPROFILE {
            get {
                return ResourceManager.GetString("ACCOUNT_EDITPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNT_LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ACCOUNT_LOGIN_SUBMITBUTTON {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_SUBMITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ACCOUNT_LOGIN_USERNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase history.
        /// </summary>
        public static string ACCOUNT_PURCHASEHISTORY {
            get {
                return ResourceManager.GetString("ACCOUNT_PURCHASEHISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ACCOUNT_REGISTER_CONFIRMPASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_CONFIRMPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ACCOUNT_REGISTER_EMAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string ACCOUNT_REGISTER_FIRSTNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ACCOUNT_REGISTER_LANGUAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNT_REGISTER_PASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ACCOUNT_REGISTER_SUBMIT {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ACCOUNT_REGISTER_SURNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string ACCOUNT_REGISTER_TIMEZONE {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_TIMEZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ACCOUNT_REGISTER_USERNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ACCOUNT_REGISTERTITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTERTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile changed success.
        /// </summary>
        public static string ACCOUNT_SAVEPROFILESUCCESS {
            get {
                return ResourceManager.GetString("ACCOUNT_SAVEPROFILESUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success register.
        /// </summary>
        public static string ACCOUNT_SUCCESSREGISTER {
            get {
                return ResourceManager.GetString("ACCOUNT_SUCCESSREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epam Training application.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some was wrong while payment occured.
        /// </summary>
        public static string ERROR_PAYMENTFAILED {
            get {
                return ResourceManager.GetString("ERROR_PAYMENTFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string EVENT_AVAILABILITY {
            get {
                return ResourceManager.GetString("EVENT_AVAILABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date.
        /// </summary>
        public static string EVENT_EVENTDATE {
            get {
                return ResourceManager.GetString("EVENT_EVENTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select place, where you want to seat.
        /// </summary>
        public static string EVENT_ISMTITLE {
            get {
                return ResourceManager.GetString("EVENT_ISMTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to checkout.
        /// </summary>
        public static string EVENT_PROCEED_TO_CHECKOUT {
            get {
                return ResourceManager.GetString("EVENT_PROCEED_TO_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event list.
        /// </summary>
        public static string EVENTS_EVENTLISTTITLE {
            get {
                return ResourceManager.GetString("EVENTS_EVENTLISTTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit events.
        /// </summary>
        public static string MAIN_EDITEVENTS {
            get {
                return ResourceManager.GetString("MAIN_EDITEVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string MAIN_EVENTS {
            get {
                return ResourceManager.GetString("MAIN_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MAIN_LOGIN {
            get {
                return ResourceManager.GetString("MAIN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MAIN_LOGOUT {
            get {
                return ResourceManager.GetString("MAIN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment end succesfull.
        /// </summary>
        public static string MAIN_PAYMENTSUCCESS {
            get {
                return ResourceManager.GetString("MAIN_PAYMENTSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MAIN_PROFILE {
            get {
                return ResourceManager.GetString("MAIN_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string MAIN_REGISTER {
            get {
                return ResourceManager.GetString("MAIN_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MANAGER_EDIT_DELETEEVENT {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_DELETEEVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MANAGER_EDIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MANAGER_EDIT_EDIT {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event list.
        /// </summary>
        public static string MANAGER_EDIT_EVENTSTITLE {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_EVENTSTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image link.
        /// </summary>
        public static string MANAGER_EDIT_IMGURL {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_IMGURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string MANAGER_EDIT_LAYOUT {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string MANAGER_EDIT_NAME {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string MANAGER_EDIT_SAVE {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time.
        /// </summary>
        public static string MANAGER_EDIT_TIME {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MANAGER_EDIT_TITLE {
            get {
                return ResourceManager.GetString("MANAGER_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full price.
        /// </summary>
        public static string PAYMENT_FULLPRICETITLE {
            get {
                return ResourceManager.GetString("PAYMENT_FULLPRICETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can buy just via account balance.
        /// </summary>
        public static string PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat, which will you buy.
        /// </summary>
        public static string PAYMENT_SEATSTITLE {
            get {
                return ResourceManager.GetString("PAYMENT_SEATSTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string PAYMENT_SUBMIT {
            get {
                return ResourceManager.GetString("PAYMENT_SUBMIT", resourceCulture);
            }
        }
    }
}
