CREATE TABLE [dbo].[Seat](
	[Id] [int] IDENTITY(1,1),
	[AreaId] [int] NOT NULL,
	[Row] [int] NOT NULL,
	[Number] [int] NOT NULL,
 CONSTRAINT [PK_Seat] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Seat]  WITH CHECK ADD  CONSTRAINT [FK_Seat_Area] FOREIGN KEY([AreaId])
REFERENCES [dbo].[Area] ([Id])
GO

ALTER TABLE [dbo].[Seat] CHECK CONSTRAINT [FK_Seat_Area]